name: Generate ASCII Art

on: [push]
jobs:
  Generate-ASCII-Art:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Install Cowsay
        run: |
          sudo apt-get update && sudo apt-get install -y cowsay

      - name: Execute Cowsay to Generate ASCII Art
        run: |
          cowsay -f dragon "Run for cover, I am a dragon! .... RAWR" >> dragon.txt

      - name: Display Generated ASCII Art
        run: |
          cat dragon.txt

      - name: List  files
        run: |
          ls -ltra


        