name: Generate ASCII Art

on: [push]
jobs:
  Generate-ASCII-Art:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: List  files
        run: |
          ls -ltra

      - name: Executing Shell Scripts
        run: |
          chmod +x ascii-script.sh
          ./ascii-script.sh
        