name: Generate ASCII Art

on: [push]
jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay
        run: sudo apt-get install -y cowsay

      - name: Executing Shell Scripts
        run: |
          chmod +x ascii-script.sh
          ./ascii-script.sh

      - name: Sleep for 30 secs
        run: sleep 30
        
  test_job_2:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 10 secs
        run: sleep 10

      - name: Check if the word "dragon" exists in the file
        run: grep -i "dragon" dragon.txt

  deploy_job_3:
    runs-on: ubuntu-latest
    steps:
      - name: Read file
        run: cat dragon.txt

      - name: Deploy
        run: echo Deploying ......